server:
  port: 8081

spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.42.15.201:3306/lovenotebook230512?serverTimezone=Asia/Shanghai
      username: root
      password: 1312004620a

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  #      id-type: auto

  #打印sql及执行过程
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl